// @ts-nocheck
/**
 * Deno copy of @ori/event-decoder. Kept in sync via scripts/sync-edge-decoder.sh
 * (runs during supabase functions deploy). Source of truth lives at
 * packages/event-decoder/src/ — do not edit this file by hand.
 *
 * Why a copy and not an import: Supabase Edge Runtime's import map can't
 * resolve workspace packages like `@ori/event-decoder`. It could pull from a
 * raw GitHub URL, but that fails for private repos and creates a network
 * dependency every cold start. Copying is boring but works.
 *
 * Last sync: (managed by sync script; check git for drift)
 */
import { bech32 } from 'https://esm.sh/bech32@2.0.0'

// ─── types.ts ─────────────────────────────────────────────────────────

export interface BaseEvent {
  kind: string
  height: bigint
  txIndex: number
}

export interface TipEvent extends BaseEvent {
  kind: 'tip'
  tipper: string
  creator: string
  grossAmount: bigint
  netAmount: bigint
  feeAmount: bigint
  denom: string
  message: string
}
export interface PaymentEvent extends BaseEvent {
  kind: 'payment'
  from: string
  to: string
  amount: bigint
  denom: string
  memo: string
  chatId: string
}
export interface PaymentBatchEvent extends BaseEvent {
  kind: 'payment_batch'
  from: string
  recipientCount: number
  totalAmount: bigint
  denom: string
  batchId: string
}
export interface GiftCreatedEvent extends BaseEvent {
  kind: 'gift_created'
  id: string
  sender: string
  amount: bigint
  denom: string
  theme: number
  mode: number
  secretHashHex: string
  expiresAt: number
}
export interface BadgeEvent extends BaseEvent {
  kind: 'badge'
  recipient: string
  badgeType: number
  level: number
  metadataUri: string
}
export interface WagerProposedEvent extends BaseEvent {
  kind: 'wager_proposed'
  wagerId: string
  proposer: string
  accepter: string
  arbiter: string
  amount: bigint
  denom: string
  claim: string
}
export interface FollowedEvent extends BaseEvent {
  kind: 'followed'
  from: string
  to: string
}
export interface UnfollowedEvent extends BaseEvent {
  kind: 'unfollowed'
  from: string
  to: string
}

export type DecodedEvent =
  | TipEvent
  | PaymentEvent
  | PaymentBatchEvent
  | GiftCreatedEvent
  | BadgeEvent
  | WagerProposedEvent
  | FollowedEvent
  | UnfollowedEvent

// ─── runtime.ts (Deno-compatible) ────────────────────────────────────

function b64ToUtf8(b64: string): string {
  const bin = atob(b64)
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  return new TextDecoder('utf-8').decode(bytes)
}

function bytesOrStringToHex(input: unknown): string {
  if (typeof input === 'string') {
    const clean = input.startsWith('0x') ? input.slice(2) : input
    if (/^[0-9a-f]+$/i.test(clean)) return clean.toLowerCase()
    return ''
  }
  if (Array.isArray(input)) {
    let hex = ''
    for (const n of input) {
      hex += ((Number(n) & 0xff)).toString(16).padStart(2, '0')
    }
    return hex
  }
  return ''
}

function hexToBytes(hex: string): Uint8Array {
  let h = hex.startsWith('0x') ? hex.slice(2) : hex
  if (h.length % 2 === 1) h = '0' + h
  const out = new Uint8Array(h.length / 2)
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16)
  }
  return out
}

function safeJson(s: string): unknown {
  try {
    return JSON.parse(s)
  } catch {
    return null
  }
}

// ─── address.ts ──────────────────────────────────────────────────────

function normalizeAddress(raw: string): string {
  if (!raw) return ''
  if (raw.startsWith('init1')) return raw
  let clean = raw.startsWith('0x') ? raw.slice(2) : raw
  clean = clean.replace(/^0+/, '') || '0'
  if (clean.length % 2 === 1) clean = '0' + clean
  if (clean.length > 40) clean = clean.slice(-40)
  clean = clean.padStart(40, '0')
  try {
    const bytes = hexToBytes(clean)
    const words = bech32.toWords(bytes)
    return bech32.encode('init', words)
  } catch {
    return raw
  }
}

// ─── decoder.ts ──────────────────────────────────────────────────────

interface RawAttr { key: string; value: string }
interface RawEvent { type: string; attributes: RawAttr[] }
interface BlockResultsResponse {
  result?: {
    txs_results?: Array<{ code?: number; events?: RawEvent[] }>
    finalize_block_events?: RawEvent[]
  }
}

export function parseBlockResults(
  body: BlockResultsResponse,
  height: bigint,
): DecodedEvent[] {
  const out: DecodedEvent[] = []
  const txs = body.result?.txs_results ?? []

  for (let txIndex = 0; txIndex < txs.length; txIndex++) {
    const tx = txs[txIndex]
    if (!tx) continue
    if (tx.code && tx.code !== 0) continue
    for (const ev of tx.events ?? []) {
      const decoded = decodeEvent(ev, height, txIndex)
      if (decoded) out.push(decoded)
    }
  }

  for (const ev of body.result?.finalize_block_events ?? []) {
    const decoded = decodeEvent(ev, height, -1)
    if (decoded) out.push(decoded)
  }

  return out
}

function decodeEvent(ev: RawEvent, height: bigint, txIndex: number): DecodedEvent | null {
  if (ev.type !== 'move') return null
  const tag = readAttr(ev, 'type_tag')
  const dataStr = readAttr(ev, 'data')
  if (!tag || !dataStr) return null
  const data = safeJson(dataStr)
  if (!data || typeof data !== 'object') return null

  const d = data as Record<string, unknown>

  if (tag.endsWith('::tip_jar::TipSent')) {
    const tipper = normalizeAddress(String(d.tipper ?? ''))
    const creator = normalizeAddress(String(d.creator ?? ''))
    if (!tipper || !creator) return null
    return {
      kind: 'tip', height, txIndex, tipper, creator,
      grossAmount: toBigInt(d.gross_amount),
      netAmount: toBigInt(d.net_amount),
      feeAmount: toBigInt(d.fee_amount),
      denom: String(d.denom ?? ''),
      message: String(d.message ?? ''),
    }
  }
  if (tag.endsWith('::payment_router::PaymentSent')) {
    const from = normalizeAddress(String(d.from ?? ''))
    const to = normalizeAddress(String(d.to ?? ''))
    if (!from || !to) return null
    return {
      kind: 'payment', height, txIndex, from, to,
      amount: toBigInt(d.amount),
      denom: String(d.denom ?? ''),
      memo: String(d.memo ?? ''),
      chatId: String(d.chat_id ?? ''),
    }
  }
  if (tag.endsWith('::payment_router::BatchPaymentSent')) {
    const from = normalizeAddress(String(d.from ?? ''))
    if (!from) return null
    return {
      kind: 'payment_batch', height, txIndex, from,
      recipientCount: Number(d.recipient_count ?? 0),
      totalAmount: toBigInt(d.total_amount),
      denom: String(d.denom ?? ''),
      batchId: String(d.batch_id ?? ''),
    }
  }
  if (tag.endsWith('::gift_packet::GiftCreated')) {
    const sender = normalizeAddress(String(d.sender ?? ''))
    if (!sender) return null
    return {
      kind: 'gift_created', height, txIndex,
      id: String(d.id ?? ''),
      sender,
      amount: toBigInt(d.amount),
      denom: String(d.denom ?? ''),
      theme: Number(d.theme ?? 0),
      mode: Number(d.mode ?? 0),
      secretHashHex: bytesOrStringToHex(d.secret_hash),
      expiresAt: Number(d.expires_at ?? 0),
    }
  }
  if (tag.endsWith('::achievement_sbt::BadgeAwarded')) {
    const recipient = normalizeAddress(String(d.recipient ?? ''))
    if (!recipient) return null
    return {
      kind: 'badge', height, txIndex, recipient,
      badgeType: Number(d.badge_type ?? 0),
      level: Number(d.level ?? 0),
      metadataUri: String(d.metadata_uri ?? ''),
    }
  }
  if (tag.endsWith('::wager_escrow::WagerProposed')) {
    const proposer = normalizeAddress(String(d.proposer ?? ''))
    if (!proposer) return null
    return {
      kind: 'wager_proposed', height, txIndex,
      wagerId: String(d.wager_id ?? ''),
      proposer,
      accepter: normalizeAddress(String(d.accepter ?? '')),
      arbiter: normalizeAddress(String(d.arbiter ?? '')),
      amount: toBigInt(d.amount),
      denom: String(d.denom ?? ''),
      claim: String(d.claim ?? ''),
    }
  }
  if (tag.endsWith('::follow_graph::Followed')) {
    const from = normalizeAddress(String(d.from ?? ''))
    const to = normalizeAddress(String(d.to ?? ''))
    if (!from || !to) return null
    return { kind: 'followed', height, txIndex, from, to }
  }
  if (tag.endsWith('::follow_graph::Unfollowed')) {
    const from = normalizeAddress(String(d.from ?? ''))
    const to = normalizeAddress(String(d.to ?? ''))
    if (!from || !to) return null
    return { kind: 'unfollowed', height, txIndex, from, to }
  }

  return null
}

function readAttr(ev: RawEvent, key: string): string | null {
  for (const a of ev.attributes) {
    if (a.key === key) return a.value
  }
  for (const a of ev.attributes) {
    try {
      if (b64ToUtf8(a.key) === key) return b64ToUtf8(a.value)
    } catch { /* ignore */ }
  }
  return null
}

function toBigInt(v: unknown): bigint {
  if (typeof v === 'bigint') return v
  try { return BigInt(String(v ?? '0')) } catch { return 0n }
}
